"""simplify subscription model

Revision ID: 307cd96563fc
Revises: d0951a70cd69
Create Date: 2025-02-07 21:34:34.404043

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '307cd96563fc'
down_revision: Union[str, None] = 'd0951a70cd69'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_payment_history_id', table_name='payment_history')
    op.drop_table('payment_history')
    op.drop_column('subscriptions', 'tier')
    op.drop_column('subscriptions', 'trial_end')
    op.drop_column('subscriptions', 'stripe_price_id')
    op.drop_column('subscriptions', 'cancel_at_period_end')
    op.drop_column('subscriptions', 'billing_interval')
    op.alter_column('webhooks', 'subscriber_count',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=True)
    op.alter_column('webhooks', 'rating',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               server_default=None,
               existing_nullable=True)
    op.alter_column('webhooks', 'total_ratings',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=True)
    op.drop_index('ix_webhooks_is_shared', table_name='webhooks')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_webhooks_is_shared', 'webhooks', ['is_shared'], unique=False)
    op.alter_column('webhooks', 'total_ratings',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=True)
    op.alter_column('webhooks', 'rating',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               server_default=sa.text("'0'::double precision"),
               existing_nullable=True)
    op.alter_column('webhooks', 'subscriber_count',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=True)
    op.add_column('subscriptions', sa.Column('billing_interval', postgresql.ENUM('MONTHLY', 'YEARLY', 'LIFETIME', name='billinginterval'), autoincrement=False, nullable=True))
    op.add_column('subscriptions', sa.Column('cancel_at_period_end', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('subscriptions', sa.Column('stripe_price_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('subscriptions', sa.Column('trial_end', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('subscriptions', sa.Column('tier', postgresql.ENUM('STARTED', 'PLUS', 'PRO', 'LIFETIME', name='subscriptiontier'), autoincrement=False, nullable=False))
    op.create_table('payment_history',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('subscription_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('stripe_payment_intent_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('amount', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('currency', sa.VARCHAR(length=3), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['subscription_id'], ['subscriptions.id'], name='payment_history_subscription_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='payment_history_pkey'),
    sa.UniqueConstraint('stripe_payment_intent_id', name='payment_history_stripe_payment_intent_id_key')
    )
    op.create_index('ix_payment_history_id', 'payment_history', ['id'], unique=False)
    # ### end Alembic commands ###
