"""add full_name to user

Revision ID: 3d5a730cfc09
Revises: edfef85c3fd6
Create Date: 2025-03-02 13:29:01.922717

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3d5a730cfc09'
down_revision: Union[str, None] = 'edfef85c3fd6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_support_ticket_logs_id', table_name='support_ticket_logs')
    op.drop_table('support_ticket_logs')
    op.add_column('users', sa.Column('full_name', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'full_name')
    op.create_table('support_ticket_logs',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('issue_type', postgresql.ENUM('BUG', 'FEATURE', 'QUESTION', 'ACCOUNT', name='issuetype'), autoincrement=False, nullable=False),
    sa.Column('subject', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('hubspot_ticket_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='support_ticket_logs_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='support_ticket_logs_pkey')
    )
    op.create_index('ix_support_ticket_logs_id', 'support_ticket_logs', ['id'], unique=False)
    # ### end Alembic commands ###
