"""add subscription tier fields

Revision ID: 88aa2fda8b74
Revises: 3d5a730cfc09
Create Date: 2025-03-10 15:59:14.664545

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '88aa2fda8b74'
down_revision: Union[str, None] = '3d5a730cfc09'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_support_ticket_logs_id', table_name='support_ticket_logs')
    op.drop_table('support_ticket_logs')
    op.drop_index('ix_token_service_status_id', table_name='token_service_status')
    op.drop_index('ix_token_service_status_timestamp', table_name='token_service_status')
    op.drop_table('token_service_status')
    op.drop_index('ix_token_refresh_attempts_id', table_name='token_refresh_attempts')
    op.drop_table('token_refresh_attempts')
    op.add_column('subscriptions', sa.Column('stripe_subscription_id', sa.String(), nullable=True))
    op.add_column('subscriptions', sa.Column('status', sa.String(), nullable=True))
    op.add_column('subscriptions', sa.Column('tier', sa.String(), nullable=True))
    op.add_column('subscriptions', sa.Column('is_lifetime', sa.Boolean(), nullable=True))
    op.add_column('subscriptions', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('subscriptions', sa.Column('updated_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('subscriptions', 'updated_at')
    op.drop_column('subscriptions', 'created_at')
    op.drop_column('subscriptions', 'is_lifetime')
    op.drop_column('subscriptions', 'tier')
    op.drop_column('subscriptions', 'status')
    op.drop_column('subscriptions', 'stripe_subscription_id')
    op.create_table('token_refresh_attempts',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('credential_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('attempted_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('success', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('error_message', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('response_time_ms', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('scheduled_tier', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('refresh_method', sa.VARCHAR(length=30), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['credential_id'], ['broker_credentials.id'], name='token_refresh_attempts_credential_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='token_refresh_attempts_pkey')
    )
    op.create_index('ix_token_refresh_attempts_id', 'token_refresh_attempts', ['id'], unique=False)
    op.create_table('token_service_status',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('timestamp', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('active_tokens', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('expired_tokens', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('refresh_success_count', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('refresh_fail_count', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('urgent_queue_size', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('soon_queue_size', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('normal_queue_size', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('cpu_usage', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('memory_usage', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='token_service_status_pkey')
    )
    op.create_index('ix_token_service_status_timestamp', 'token_service_status', ['timestamp'], unique=False)
    op.create_index('ix_token_service_status_id', 'token_service_status', ['id'], unique=False)
    op.create_table('support_ticket_logs',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('issue_type', postgresql.ENUM('BUG', 'FEATURE', 'QUESTION', 'ACCOUNT', name='issuetype'), autoincrement=False, nullable=False),
    sa.Column('subject', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('hubspot_ticket_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='support_ticket_logs_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='support_ticket_logs_pkey')
    )
    op.create_index('ix_support_ticket_logs_id', 'support_ticket_logs', ['id'], unique=False)
    # ### end Alembic commands ###
