"""make_billing_interval_nullable

Revision ID: 8a251c11bfb6
Revises: 62d1d0deb00a
Create Date: 2025-02-07 22:28:21.591379

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8a251c11bfb6'
down_revision: Union[str, None] = '62d1d0deb00a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('subscriptions', 'billing_interval',
               existing_type=postgresql.ENUM('MONTHLY', 'YEARLY', 'LIFETIME', name='billinginterval'),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('subscriptions', 'billing_interval',
               existing_type=postgresql.ENUM('MONTHLY', 'YEARLY', 'LIFETIME', name='billinginterval'),
               nullable=False)
    # ### end Alembic commands ###
