"""add soft delete to broker accounts

Revision ID: a79b6d518ec1
Revises: 1f01c67ddf49
Create Date: 2024-12-31 16:06:19.892051

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a79b6d518ec1'
down_revision: Union[str, None] = '1f01c67ddf49'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('broker_accounts', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.add_column('broker_accounts', sa.Column('is_deleted', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('broker_accounts', 'is_deleted')
    op.drop_column('broker_accounts', 'deleted_at')
    # ### end Alembic commands ###
