"""add_strategy_follower_quantities_table

Revision ID: adecf4b21951
Revises: 183b34d3df5c
Create Date: 2025-02-02 21:49:14.849431

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'adecf4b21951'
down_revision: Union[str, None] = '183b34d3df5c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'activated_strategies', 'broker_accounts', ['leader_account_id'], ['account_id'])
    op.alter_column('strategy_follower_quantities', 'strategy_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('strategy_follower_quantities', 'account_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('webhooks', 'is_shared',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               nullable=True)
    op.drop_column('webhooks', 'description')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('webhooks', sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True))
    op.alter_column('webhooks', 'is_shared',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               nullable=False)
    op.alter_column('strategy_follower_quantities', 'account_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('strategy_follower_quantities', 'strategy_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_constraint(None, 'activated_strategies', type_='foreignkey')
    # ### end Alembic commands ###
