"""add_support_ticket_system

Revision ID: edfef85c3fd6
Revises: ce1ad660ba6c
Create Date: 2025-02-28 15:52:30.489959

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'edfef85c3fd6'
down_revision: Union[str, None] = 'ce1ad660ba6c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
