"""update_user_model_relationships

Revision ID: fe578aee2d61
Revises: d4a2ec0a3b70
Create Date: 2025-02-10 23:38:49.587414

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fe578aee2d61'
down_revision: Union[str, None] = 'd4a2ec0a3b70'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
